version: "3"
services:
  node:
    image: ${PROJECT:-myapp}/node:latest
    container_name: ${PROJECT:-myapp}_node
    build:
      context: .
      dockerfile: ${NODE_DOCKERFILE:-./node.Dockerfile}
      args:
        environment: ${ENVIRONMENT:-production}
        node_src: ${NODE_SRC:-./node}
    restart: always

  nginx:
    image: ${PROJECT:-myapp}/nginx:latest
    container_name: ${PROJECT:-myapp}_nginx
    build:
      context: ./nginx
    environment:
      - DOMAINS=${DOMAINS}
      - EMAIL=${EMAIL}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
