version: "3"
services:
  node:
    image: ${PROJECT_NAME}/node:latest
    container_name: ${PROJECT_NAME}_node
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        node_env: ${ENVIRONMENT}
    volumes:
      - ./node:/node
    expose:
      - ${NODE_PORT}
    restart: always

  nginx:
    image: ${PROJECT_NAME}/nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: ./nginx
      args:
        domain: ${DOMAIN}
        response: proxy_pass http://node:${NODE_PORT}
    # depends_on:
    #   - certbot
    #   - node
    volumes:
      - ./certbot/letsencrypt/:/data/letsencrypt
      - ./certbot/certs:/data/certs
    ports:
      - 80:80
      - 443:443
    restart: always

  certbot:
    image: ${PROJECT_NAME}/certbot:latest
    container_name: ${PROJECT_NAME}_certbot
    build:
      context: .
      dockerfile: ./certbot/Dockerfile
    volumes:
      - ./certbot/letsencrypt:/data/letsencrypt
      - ./certbot/certs:/data/certs
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      ENVIRONMENT: ${ENVIRONMENT}
    tty: true
